### ISSUE TITLE
Issue with jar_paths

### ISSUE THREAD

**Issue by ericlxbgit** [jaehyeon-kim/flink-demos#19]
If run on windows local machine, the file path of jar may need to be updated from 
jar_paths = tuple(
            [f"**file://{**os.path.join(CURRENT_DIR, 'jars', name)}" for name in jar_files]
        )
to
jar_paths = tuple(
            [f"**file:///**{os.path.join(CURRENT_DIR, 'jars', name)}" for name in jar_files]
        )

Such issue can be found at [[flink-demos](https://github.com/jaehyeon-kim/flink-demos/tree/master)/[building-pyflink-apps](https://github.com/jaehyeon-kim/flink-demos/tree/master/building-pyflink-apps)/[src](https://github.com/jaehyeon-kim/flink-demos/tree/master/building-pyflink-apps/src/s10_deserialization.py)](https://github.com/jaehyeon-kim/flink-demos/blob/master/building-pyflink-apps/src/s10_deserialization.py)

I also checked the following flink documents: 
https://nightlies.apache.org/flink/flink-docs-release-1.18/docs/dev/python/dependency_management/

The problem is on windows machine, {os.path.join(CURRENT_DIR, 'jars', name) will return the path like "D:\\abc\def\\xyz.jar", then file:**//**{os.path.join(CURRENT_DIR, 'jars', name)} will be file://D:\\abc\def\\xyz.jar, which would not work. So on windows system, the expression may need to be updated to file:**///**{os.path.join(CURRENT_DIR, 'jars', name)} .

**Comment by jaehyeon-kim** [comment]
Can you leave a link of it? I don't locate one.

**Comment by ericlxbgit** [comment]
> Can you leave a link of it? I don't locate one.

I just updated my question above. I think it might be a system-oriented issue too.

Thank you so much! All in all, your articals and sample code are truely awsome and help me a lot to dive into Flink!
