### ISSUE TITLE
(Terraform) RuntimeError: Python interpreter version equal to defined lambda runtime (python3.8) should be available in system PATH

### ISSUE THREAD

**Issue by ericlxbgit** [jaehyeon-kim/flink-demos#20]
Hi Kim, 

When I ran "terraform plan" for the tf script in infra folder, like below: 
(.venv) PS D:\Projects\GitHub\flink-demos-master\real-time-streaming-aws\infra> terraform plan -var 'producer_to_create=true'

I ran into the following issue. could you shed a light on this? 

![image](https://github.com/user-attachments/assets/99f417bf-f75f-4385-9e87-73d549227e31)

Thank you so much!

**Comment by jaehyeon-kim** [comment]
Looks like it is a Windows related issue. Can you try on WSL2?

**Comment by jaehyeon-kim** [comment]
Is there an update? Please close if it gets fixed.

**Comment by ericlxbgit** [comment]
Thank you so much!!!!!
